### ISSUE TITLE
[FEATURE REQUEST] Add Discord Plugin

### ISSUE THREAD

**Issue by NullSoldier** [NullSoldier/serverthrall#47]

**Comment by THCue** [comment]
This would be great +1

**Comment by NullSoldier** [comment]
@THCue what type of things would you want the discord plugin to do? I can make it so anything can be sent, but what type of messages?

**Comment by THCue** [comment]
Okay am pulling some of this off this guy since he quit working on it but it did work smooth and might give you some ideas.

https://github.com/prom3theu5/ConanExilesServerUpdater

Maybe even put in some of them things as well. Besides all that the program as been working great I've had it lock up and cant find the child process a couple time. If that happens again I'll get more info.

**Comment by NullSoldier** [comment]
How about for v1 it'll announce when a restart will happen and then restart
after that specified time.

**Comment by THCue** [comment]
A 5min or whatever time imputed announcement would be nice for players.

**Comment by calmcacil** [comment]
shouldnt be that hard to just use webhooks to send an update when the server has crashed (been autorestarted due to crash) or updated due to  new build etc and just output that as a webhook.

The webhook documentation is here. https://discordapp.com/developers/docs/resources/webhook

**Comment by tt-jspafford** [comment]
This is finished, will be released in the next version.

**Comment by tt-jspafford** [comment]
This is finished, will be released in the next version.

**Comment by NullSoldier** [comment]
This is finished, will be released in the next version.

**Comment by NullSoldier** [comment]
Shipped https://github.com/NullSoldier/serverthrall/releases/tag/v2.1.0
