### ISSUE TITLE
Support for auto updating mods 

### ISSUE THREAD

**Issue by Doorstop2** [NullSoldier/serverthrall#58]
Please add support for auto updating mods maybe in the cfg have something with mod ids using 123456,123456,123456 etc...

**Comment by NullSoldier** [comment]
I already mostly finished the work for this feature, but at the time mods weren't widely used because clients don't auto download mods. If this is a feature that enough people want, I can finish that work. The code is sitting in the branch here, https://github.com/NullSoldier/serverthrall/tree/mod-updater

**Comment by Doorstop2** [comment]
Sweet if you make it announce in discord when there is a mod update and you can now use the rcon to announce in game so players will know if its a mod update or a game update. https://conanexiles.gamepedia.com/Rcon 

I have tested this using the mcrcon tool which i was able to login to rcon and run/send broadcast cmds

**Comment by NullSoldier** [comment]
This is planned for the next major patch. I'll post an update here once the PR gets opened.

**Comment by Doorstop2** [comment]
Sweet thanks 👍

**Comment by NullSoldier** [comment]
This is done and released.
